import type { LayerSpecification } from "maplibre-gl";

/**
 * The layers of MapTiler's `outdoor-v2` style as fetched on 2026-09-30, cut down to what
 * `basemapTheme.ts` reads: id, type, source-layer and which colour paint properties
 * each declares (values are placeholders — the real ones are MapTiler's). The test
 * suite runs offline, so this stands in for the live style.
 */
const ROWS: Array<[id: string, type: string, sourceLayer: string, colorProperties: string[]]> = [
  ["Background", "background", "", ["background-color"]],
  ["Scrub", "fill", "globallandcover", ["fill-color"]],
  ["Tree", "fill", "globallandcover", ["fill-color"]],
  ["Forest", "fill", "globallandcover", ["fill-color"]],
  ["Wood", "fill", "landcover", ["fill-color"]],
  ["Grass", "fill", "landcover", ["fill-color"]],
  ["Sand", "fill", "landcover", ["fill-color"]],
  ["Glacier", "fill", "landcover", ["fill-color"]],
  ["Residential", "fill", "landuse", ["fill-color"]],
  ["Industrial", "fill", "landuse", ["fill-color"]],
  ["Commercial", "fill", "landuse", ["fill-color"]],
  ["Military", "fill", "landuse", ["fill-color", "fill-outline-color"]],
  ["Cemetery", "fill", "landuse", ["fill-color"]],
  ["Hospital", "fill", "landuse", ["fill-color"]],
  ["Stadium", "fill", "landuse", ["fill-color"]],
  ["Hillshade", "hillshade", "", ["hillshade-accent-color", "hillshade-highlight-color", "hillshade-shadow-color"]],
  ["Park", "fill", "park", ["fill-color"]],
  ["Park outline", "line", "park", ["line-color"]],
  ["Contour index", "line", "contour", ["line-color"]],
  ["Glacier contour index", "line", "contour", ["line-color"]],
  ["Contour", "line", "contour", ["line-color"]],
  ["Glacier contour", "line", "contour", ["line-color"]],
  ["Cliff line", "line", "mountain_peak", ["line-color"]],
  ["Cliff", "line", "mountain_peak", ["line-color"]],
  ["Contour labels", "symbol", "contour", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Glacier contour labels", "symbol", "contour", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["River tunnel", "line", "waterway", ["line-color"]],
  ["River", "line", "waterway", ["line-color"]],
  ["Water", "fill", "water", ["fill-color"]],
  ["Aeroway", "fill", "aeroway", ["fill-color"]],
  ["Runway", "line", "aeroway", ["line-color"]],
  ["Taxiway", "line", "aeroway", ["line-color"]],
  ["Ferry", "line", "transportation", ["line-color"]],
  ["Tunnel path", "line", "transportation", ["line-color"]],
  ["Tunnel", "line", "transportation", ["line-color"]],
  ["Railway tunnel", "line", "transportation", ["line-color"]],
  ["Railway tunnel dash", "line", "transportation", ["line-color"]],
  ["Bridge", "fill", "transportation", ["fill-color", "fill-outline-color"]],
  ["Pier", "fill", "transportation", ["fill-color"]],
  ["Road network", "line", "transportation", ["line-color"]],
  ["Steps", "line", "transportation", ["line-color"]],
  ["Track", "line", "transportation", ["line-color"]],
  ["Path minor", "line", "transportation", ["line-color"]],
  ["Path", "line", "transportation", ["line-color"]],
  ["Pedestrian outline", "line", "transportation", ["line-color"]],
  ["Pedestrian", "line", "transportation", ["line-color"]],
  ["Minor railway", "line", "transportation", ["line-color"]],
  ["Minor railway hatching", "line", "transportation", ["line-color"]],
  ["Major railway", "line", "transportation", ["line-color"]],
  ["Major railway dash", "line", "transportation", ["line-color"]],
  ["Military limit", "line", "landuse", ["line-color"]],
  ["Building", "fill", "building", ["fill-color", "fill-outline-color"]],
  ["Trails outline", "line", "trail", ["line-color"]],
  ["Bicycle outline", "line", "trail", ["line-color"]],
  ["Other trails", "line", "trail", ["line-color"]],
  ["Bicycle local", "line", "trail", ["line-color"]],
  ["Yellow trail", "line", "trail", ["line-color"]],
  ["Green trail", "line", "trail", ["line-color"]],
  ["Blue trail", "line", "trail", ["line-color"]],
  ["Brown trail", "line", "trail", ["line-color"]],
  ["Black trail", "line", "trail", ["line-color"]],
  ["Purple trail", "line", "trail", ["line-color"]],
  ["Orange trail", "line", "trail", ["line-color"]],
  ["Red trail", "line", "trail", ["line-color"]],
  ["Longdistance trail outline", "line", "trail", ["line-color"]],
  ["Longdistance trail", "line", "trail", ["line-color"]],
  ["Via ferrata outline", "line", "trail", ["line-color"]],
  ["Via ferrata", "line", "trail", ["line-color"]],
  ["Via ferrata symbol", "symbol", "trail", ["text-color", "text-halo-color"]],
  ["Bicycle longdistance", "line", "trail", ["line-color"]],
  ["Minor lift", "line", "transportation", ["line-color"]],
  ["Minor lift dash", "line", "transportation", ["line-color"]],
  ["Chair lift", "line", "transportation", ["line-color"]],
  ["Chair lift dash", "line", "transportation", ["line-color"]],
  ["Cable car", "line", "transportation", ["line-color"]],
  ["Cable car dash", "line", "transportation", ["line-color"]],
  ["Aerialway labels", "symbol", "transportation_name", ["text-color", "text-halo-color"]],
  ["Road labels", "symbol", "transportation_name", ["text-color", "text-halo-color"]],
  ["Other border", "line", "boundary", ["line-color"]],
  ["Disputed border", "line", "boundary", ["line-color"]],
  ["Country border", "line", "boundary", ["line-color"]],
  ["River labels", "symbol", "waterway", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Lakeline labels", "symbol", "water_name", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Ocean labels", "symbol", "water_name", ["icon-halo-color", "text-color", "text-halo-color"]],
  ["Sea labels", "symbol", "water_name", ["text-color", "text-halo-color"]],
  ["Lake labels", "symbol", "water_name", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Outdoor shop", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Sport", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Outdoor water", "symbol", "outdoor_poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Transport", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Food", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Park labels", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Healthcare", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Tourism", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Culture", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Outdoor", "symbol", "outdoor_poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Station", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Castle", "symbol", "poi", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Volcano labels (US)", "symbol", "mountain_peak", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Volcano labels", "symbol", "mountain_peak", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Peak labels (US)", "symbol", "mountain_peak", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Peak labels", "symbol", "mountain_peak", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Place labels", "symbol", "place", ["text-color", "text-halo-color"]],
  ["Village labels", "symbol", "place", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Airport labels", "symbol", "aerodrome_label", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Longdistance trail labels", "symbol", "trail", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Bicycle longdistance labels", "symbol", "trail", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Protected area labels", "symbol", "park", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["Town labels", "symbol", "place", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["State labels", "symbol", "place", ["icon-halo-color", "text-color", "text-halo-color"]],
  ["National park labels", "symbol", "park", ["icon-color", "icon-halo-color", "text-color", "text-halo-color"]],
  ["City labels", "symbol", "place", ["icon-halo-color", "text-color", "text-halo-color"]],
  ["Country labels", "symbol", "place", ["text-color", "text-halo-color"]],
  ["Continent labels", "symbol", "place", ["icon-color", "text-color", "text-halo-color"]],
];

export const OUTDOOR_V2_LAYERS = ROWS.map(([id, type, sourceLayer, colorProperties]) => ({
  id,
  type,
  ...(sourceLayer ? { source: "maptiler_planet", "source-layer": sourceLayer } : {}),
  paint: Object.fromEntries(colorProperties.map((p) => [p, "placeholder"])),
})) as unknown as LayerSpecification[];
