/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 94a5a5ac86aa3758ee8a62d6573d883a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		SHADOW_TILES: R2Bucket;
		ALLOWED_ORIGIN: "https://shademapnav.vercel.app";
	}
}
interface Env extends Cloudflare.Env {}
